name: Install Action
description: Initializes a conda environment
inputs:
  name:
    description: The name of the task
    required: true
  channels:
    description: The conda channels to fetch packages from
    default: defaults
  channel-priority:
    description: Channel priority determines if packages in lower priority channels are considered if a package with the same name appears in a higher priority channel.
    required: false
    default: flexible
  conda-update:
    description: Whether to update conda
    required: false
    default: 'true'
  python-version:
    description: The Python version to install
    required: true
    default: '3.7'
  envs:
    description: The environment to initialize
    required: true
    default: -o examples
  nodejs:
    description: Whether to install nodejs in the base environment
    required: false
    default: 'false'
  nodejs-version:
    description: nodejs version to install in the base environment
    required: false
    default: '16.x'
  cache:
    description: Whether to enable caching
    required: false
    default: 'false'
  opengl:
    description: Whether to install openGL
    required: false
    default: 'false'
  playwright:
    description: Whether to install playwright
    required: false
    default: 'false'
  conda-mamba:
    description: Whether to use conda or mamba
    required: false
    default: 'conda'
    options:
      - 'conda'
      - 'mamba'
outputs:
  cache-hit:
    description: Whether the cache was hit
    value: ${{ steps.cache.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: "100"
      # Forcing fetch to avoid 'would clobber existing tag', as the previous step
      # fetches tags already.
    - run: git fetch --prune --tags --unshallow --force
      shell: bash -el {0}
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        conda-version: "22.11.1"
        auto-update-conda: ${{ inputs.conda-update }}
        # use-only-tar-bz2: ${{ inputs.cache }}  # Does not give latest version
    - run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      shell: bash -el {0}
    - if: runner.os == 'Windows'
      run: echo "ENVS_PATH=${{ format('{0}\{1}', env.CONDA, 'envs') }}" >> $GITHUB_ENV
      shell: bash -el {0}
    - if: runner.os != 'Windows'
      run: echo "ENVS_PATH=${{ format('{0}/{1}', env.CONDA, 'envs') }}" >> $GITHUB_ENV
      shell: bash -el {0}
    - if: inputs.cache == 'true'
      uses: actions/cache@v3
      with:
        path: ${{ env.ENVS_PATH }}
        key: ${{ inputs.name  }}-${{ runner.os }}-${{ inputs.conda-mamba }}-${{ inputs.python-version }}-${{ hashFiles('setup.py') }}-${{ env.TODAY }}
      id: cache
    - if: inputs.conda-mamba == 'mamba' && steps.cache.outputs.cache-hit != 'true'
      run: |
        echo "MAMBA_NO_BANNER=1" >> $GITHUB_ENV
        conda install "mamba==1.3.0" -c conda-forge -n base
        conda run -n base mamba init --all
      shell: bash -el {0}
    - if: inputs.nodejs == 'true' && steps.cache.outputs.cache-hit != 'true'
      uses: actions/setup-node@v1
      with:
       node-version: ${{ inputs.nodejs-version }}
    - if: steps.cache.outputs.cache-hit != 'true'
      run: |
        conda create -n test-environment
        conda activate test-environment
        IFS="," read -a channels_array <<< ${{ inputs.channels }}
        for channel in "${channels_array[@]}"; do
          if [ "$channel" = "nodefaults" ]
          then
            echo "Remove defaults channel"
            conda config --remove channels defaults
            conda config --env --remove channels defaults
          else
            echo "Add channel $channel"
            conda config --env --append channels ${channel}
          fi
        done
        conda config --env --set channel_priority ${{ inputs.channel-priority }}
        conda config --show-sources
        conda info
        ${{ inputs.conda-mamba }} install python=${{ inputs.python-version }} pyctdev
      shell: bash -el {0}
    - if: inputs.cache == 'true' && steps.cache.outputs.cache-hit == 'true'
      run: |
        conda activate test-environment
        pip install -e . --no-deps --no-build-isolation
      shell: bash -el {0}
    - if: inputs.cache != 'true' || steps.cache.outputs.cache-hit != 'true'
      # Need || echo "Keep going" and pip install again to deal with
      # when pyctdev updates CPython itself. Dangerous as that could
      # hide other issues.
      run: |
        conda activate test-environment
        doit develop_install ${{ inputs.envs }} --conda-mode=${{ inputs.conda-mamba }} || echo "Keep going"
        pip install -e . --no-deps --no-build-isolation
      shell: bash -el {0}
    - if: inputs.opengl == 'true' && runner.os == 'Windows'
      run: |
        git clone --depth 1 https://github.com/pyvista/gl-ci-helpers.git
        powershell gl-ci-helpers/appveyor/install_opengl.ps1
      shell: bash -el {0}
    - if: inputs.opengl == 'true' && runner.os == 'Linux'
      run: |
        sudo apt-get install libglu1-mesa
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24
        sleep 3
      shell: bash -el {0}
    - if: inputs.opengl == 'true' && runner.os == 'Linux' && (inputs.cache != 'true' || steps.cache.outputs.cache-hit != 'true')
      run: |
        conda activate test-environment
        ${{ inputs.conda-mamba }} install mesalib
      shell: bash -el {0}
    - if: inputs.playwright == 'true' && (inputs.cache != 'true' || steps.cache.outputs.cache-hit != 'true')
      run: |
        conda activate test-environment
        pip install playwright pytest-playwright
      shell: bash -el {0}
    - if: inputs.playwright == 'true'
      run: |
        conda activate test-environment
        playwright install chromium
      shell: bash -el {0}
    - run: |
        conda activate test-environment
        doit env_capture
      shell: bash -el {0}
